// Generated by CoffeeScript 1.5.0
var config, fileConfig, fs, _;

fs = require('fs');

_ = require('lodash');

config = {
  src: 'src',
  out: '.',
  server: {
    script: 'index.js',
    env: {}
  },
  clone: [],
  mappings: [],
  builders: {
    js: {},
    json: {},
    coffee: {},
    jade: {
      amd: true
    },
    stylus: {
      url: {
        paths: ['public']
      },
      paths: ['public/images']
    }
  }
};

if (fs.existsSync('squid.json')) {
  fileConfig = JSON.parse(fs.readFileSync('squid.json'));
  config = _(fileConfig).defaults(config);
}

Object.keys(config.builders).forEach(function(b) {});

config.fileFilter = function(f) {
  return /\.(js|coffee|styl|jade|json)$/.test(f);
};

config.filter = function(f, stat) {
  return stat.isDirectory() || config.fileFilter(f);
};

module.exports = config;
