// Generated by CoffeeScript 1.5.0
var BuildError, Builder, JSONBuilder, _ref,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

_ref = require('./Builder'), Builder = _ref.Builder, BuildError = _ref.BuildError;

module.exports = JSONBuilder = (function(_super) {

  __extends(JSONBuilder, _super);

  function JSONBuilder() {
    JSONBuilder.__super__.constructor.apply(this, arguments);
  }

  JSONBuilder.prototype.fileExt = '.json';

  JSONBuilder.prototype.outExt = '.json';

  JSONBuilder.prototype._build = function(file, code, refresh, cb) {
    try {
      JSON.parse(code);
      return this.write(code, file, cb);
    } catch (err) {
      return cb(new BuildError(file, err));
    }
  };

  return JSONBuilder;

})(Builder);
