// Generated by CoffeeScript 1.3.3
(function() {
  var logFolder, path, winston;

  path = require('path');

  winston = require('winston');

  require('winston-growl');

  /*
  Setup loggers container
  */


  logFolder = path.join(__dirname, '../../data/log/');

  winston.loggers.add('util', {
    console: {
      colorize: true,
      padLevels: true
    }
  });

  winston.loggers.add('notifier', {
    growl: {}
  });

  module.exports = winston.loggers;

}).call(this);
