// Generated by CoffeeScript 1.6.2
var Growl, level, winston;

winston = require('winston');

Growl = require('winston-growl');

level = process.env.DEBUG ? 'debug' : 'info';

module.exports = {
  logger: new winston.Logger({
    transports: [
      new winston.transports.Console({
        colorize: true,
        padLevels: true,
        level: level
      })
    ]
  }),
  notifier: new winston.Logger({
    transports: [
      new Growl, new winston.transports.Console({
        colorize: true,
        padLevels: true,
        level: 'error'
      })
    ]
  })
};
