// Generated by CoffeeScript 1.4.0
(function() {
  var winston;

  winston = require('winston');

  require('winston-growl');

  winston.loggers.add('util', {
    console: {
      colorize: true,
      padLevels: true
    }
  });

  winston.loggers.add('notifier', {
    growl: {}
  });

  module.exports = winston.loggers;

}).call(this);
