// Generated by CoffeeScript 1.5.0
var BuildError, Builder, CopyBuilder, fs, util, _ref,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

fs = require('fs');

util = require('util');

_ref = require('./Builder'), Builder = _ref.Builder, BuildError = _ref.BuildError;

module.exports = CopyBuilder = (function(_super) {

  __extends(CopyBuilder, _super);

  function CopyBuilder() {
    CopyBuilder.__super__.constructor.apply(this, arguments);
  }

  CopyBuilder.prototype.build = function(src, refresh, cb) {
    var outStream, srcStream;
    srcStream = fs.createReadStream(src);
    outStream = fs.createWriteStream(this.buildPath(file, this.outDir));
    return srcStream.once('open', function() {
      return util.pump(srcStream, outStream, cb);
    });
  };

  return CopyBuilder;

})(Builder);
