// Generated by CoffeeScript 1.5.0
var Coffee, Jade, Js, Json, Stylus, builders, createFactory, path, regStr;

path = require('path');

builders = [];

builders.push(Js = new require('./Js'));

builders.push(Coffee = new require('./Coffee'));

builders.push(Stylus = new require('./Stylus'));

builders.push(Jade = new require('./Jade'));

builders.push(Json = new require('./Json'));

regStr = '\\.(';

regStr += builders.map(function(Builder) {
  return Builder.prototype.fileExt.slice(1);
}).join('|');

regStr += ')$';

createFactory = function(config) {
  var Builder, factory, _i, _len;
  factory = {};
  for (_i = 0, _len = builders.length; _i < _len; _i++) {
    Builder = builders[_i];
    factory[Builder.prototype.fileExt] = new Builder(config);
  }
  factory.get = function(file) {
    return this[path.extname(file)];
  };
  return factory;
};

module.exports = {
  createFactory: createFactory,
  fileFilter: new RegExp(regStr)
};
