// Generated by CoffeeScript 1.6.3
var BuildError, Builder, JsonBuilder, _ref, _ref1,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

_ref = require('./Builder'), Builder = _ref.Builder, BuildError = _ref.BuildError;

module.exports = JsonBuilder = (function(_super) {
  __extends(JsonBuilder, _super);

  function JsonBuilder() {
    _ref1 = JsonBuilder.__super__.constructor.apply(this, arguments);
    return _ref1;
  }

  JsonBuilder.prototype.fileExt = '.json';

  JsonBuilder.prototype.outExt = '.json';

  JsonBuilder.prototype._build = function(file, code, refresh, cb) {
    var err;
    try {
      JSON.parse(code);
      return this.write(code, file, cb);
    } catch (_error) {
      err = _error;
      return cb(new BuildError(file, err));
    }
  };

  return JsonBuilder;

})(Builder);
