// Generated by CoffeeScript 1.5.0
var BuildError, Builder, CSSBuilder, OptiPng, fs, mkdirp, optimizer, path, _ref,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

path = require('path');

fs = require('fs');

mkdirp = require('mkdirp');

OptiPng = require('optipng');

_ref = require('./Builder'), Builder = _ref.Builder, BuildError = _ref.BuildError;

optimizer = new OptiPng;

module.exports = CSSBuilder = (function(_super) {

  __extends(CSSBuilder, _super);

  CSSBuilder.prototype.fileExt = '.png';

  CSSBuilder.prototype.outExt = '.png';

  function CSSBuilder() {
    CSSBuilder.__super__.constructor.apply(this, arguments);
    this.pngConfig = this.config.builders.png;
  }

  CSSBuilder.prototype.build = function(src, refresh, cb) {
    var out,
      _this = this;
    out = this.buildPath(src);
    return mkdirp(path.dirname(out), 0x1ed, function(err) {
      var outStream, srcStream;
      if (err) {
        return cb(new BuildError(out, err));
      }
      srcStream = fs.createReadStream(src);
      outStream = fs.createWriteStream(out);
      srcStream.pipe(optimizer).pipe(outStream);
      return outStream.on('close', cb);
    });
  };

  return CSSBuilder;

})(Builder);
