module.exports = builders = []
builders.push new require './Js'
builders.push new require './Coffee'
builders.push new require './Stylus'
builders.push new require './Jade'
builders.push new require './Json'
builders.push new require './Handlebars'
builders.push new require './Css'
builders.push new require './Png'
# builders.push new require './Jpg'