// Generated by CoffeeScript 1.5.0
var _this = this;

module.exports = {
  init: function(project) {
    if (!project.config.clone) {
      return;
    }
    this.clones = project.config.clone;
    return project.onBuild(this.onBuild);
  },
  onBuild: function(builder, newCode, src, next) {
    return _this.clones.forEach(function(clone) {
      var file, map;
      if (clone.match.test(src)) {
        file = builder.buildPath(src, path.resolve(clone.to));
        if (map = clone.map) {
          file = file.replace(map.from, map.to);
        }
        return mkdirp(path.dirname(file), 0x1ed, function(err) {
          if (err) {
            return next("Error cloning dir to " + file);
          }
          return fs.writeFile(file, newCode, function(err) {
            if (err) {
              return next("Error cloning dir to " + file);
            }
            return next();
          });
        });
      }
    });
  }
};
