// Generated by CoffeeScript 1.6.2
var exec, fs, path;

fs = require('fs');

path = require('path');

exec = require('child_process').exec;

module.exports = function(project) {
  if (!fs.existsSync(path.join(project.config.out, 'component.json'))) {
    return;
  }
  return project.on('build', function(src) {});
};
