// Generated by CoffeeScript 1.5.0
var exec;

exec = require('child_process').exec;

module.exports = function(project) {
  var cmd, match, reg, script, _ref;
  _ref = project.config.post_build, cmd = _ref.cmd, match = _ref.match;
  if (!cmd) {
    return;
  }
  reg = new RegExp(match || '');
  script = null;
  return project.on('build', function(src) {
    if (!reg.test(src)) {
      return;
    }
    if (script != null) {
      script.kill();
    }
    return script = exec(cmd, function(err, stdout, stderr) {
      console.log(stdout + stderr);
      return script = null;
    });
  });
};
