// Generated by CoffeeScript 1.5.0
var exec,
  _this = this;

exec = require('child_process').exec;

module.exports = {
  init: function(project) {
    if (!project.config.post_build) {
      return;
    }
    this.reg = new RegExp(config.post_build.match || '');
    this.cmd = config.post_build.cmd;
    this.script = null;
    return project.onBuild(this.onBuild);
  },
  onBuild: function(builder, newCode, src) {
    var _ref;
    if (!_this.reg.test(src)) {
      if ((_ref = _this.script) != null) {
        _ref.kill();
      }
      return _this.script = exec(_this.cmd, function(err, stdout, stderr) {
        console.log(stdout + stderr);
        return _this.script = null;
      });
    }
  }
};
